// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: internal/interfaces/proto/protobuf/newsfeed/newsfeed.proto

package newsfeed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateNewsfeedResponse_GenerateNewsfeedStatus int32

const (
	GenerateNewsfeedResponse_OK             GenerateNewsfeedResponse_GenerateNewsfeedStatus = 0
	GenerateNewsfeedResponse_USER_NOT_FOUND GenerateNewsfeedResponse_GenerateNewsfeedStatus = 1
)

// Enum value maps for GenerateNewsfeedResponse_GenerateNewsfeedStatus.
var (
	GenerateNewsfeedResponse_GenerateNewsfeedStatus_name = map[int32]string{
		0: "OK",
		1: "USER_NOT_FOUND",
	}
	GenerateNewsfeedResponse_GenerateNewsfeedStatus_value = map[string]int32{
		"OK":             0,
		"USER_NOT_FOUND": 1,
	}
)

func (x GenerateNewsfeedResponse_GenerateNewsfeedStatus) Enum() *GenerateNewsfeedResponse_GenerateNewsfeedStatus {
	p := new(GenerateNewsfeedResponse_GenerateNewsfeedStatus)
	*p = x
	return p
}

func (x GenerateNewsfeedResponse_GenerateNewsfeedStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateNewsfeedResponse_GenerateNewsfeedStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_enumTypes[0].Descriptor()
}

func (GenerateNewsfeedResponse_GenerateNewsfeedStatus) Type() protoreflect.EnumType {
	return &file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_enumTypes[0]
}

func (x GenerateNewsfeedResponse_GenerateNewsfeedStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateNewsfeedResponse_GenerateNewsfeedStatus.Descriptor instead.
func (GenerateNewsfeedResponse_GenerateNewsfeedStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescGZIP(), []int{1, 0}
}

type GenerateNewsfeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GenerateNewsfeedRequest) Reset() {
	*x = GenerateNewsfeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateNewsfeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNewsfeedRequest) ProtoMessage() {}

func (x *GenerateNewsfeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNewsfeedRequest.ProtoReflect.Descriptor instead.
func (*GenerateNewsfeedRequest) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateNewsfeedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GenerateNewsfeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  GenerateNewsfeedResponse_GenerateNewsfeedStatus `protobuf:"varint,1,opt,name=status,proto3,enum=newsfeed.GenerateNewsfeedResponse_GenerateNewsfeedStatus" json:"status,omitempty"`
	PostIds []int64                                         `protobuf:"varint,2,rep,packed,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
}

func (x *GenerateNewsfeedResponse) Reset() {
	*x = GenerateNewsfeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateNewsfeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNewsfeedResponse) ProtoMessage() {}

func (x *GenerateNewsfeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNewsfeedResponse.ProtoReflect.Descriptor instead.
func (*GenerateNewsfeedResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateNewsfeedResponse) GetStatus() GenerateNewsfeedResponse_GenerateNewsfeedStatus {
	if x != nil {
		return x.Status
	}
	return GenerateNewsfeedResponse_OK
}

func (x *GenerateNewsfeedResponse) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

var File_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto protoreflect.FileDescriptor

var file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x2f, 0x6e, 0x65,
	0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x65,
	0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x22, 0x32, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xbe, 0x01, 0x0a, 0x18, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x39, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65,
	0x65, 0x64, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x73, 0x66,
	0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x73, 0x22, 0x34, 0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x32, 0x67, 0x0a, 0x08, 0x4e,
	0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x12, 0x5b, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x12, 0x21, 0x2e, 0x6e, 0x65,
	0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e,
	0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x5f, 0x5a, 0x5d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6b, 0x68, 0x61, 0x69, 0x6c, 0x65, 0x71, 0x75, 0x61, 0x6e, 0x67, 0x33, 0x33,
	0x34, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x3b, 0x6e, 0x65, 0x77,
	0x73, 0x66, 0x65, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescOnce sync.Once
	file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescData = file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDesc
)

func file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescGZIP() []byte {
	file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescOnce.Do(func() {
		file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescData)
	})
	return file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDescData
}

var file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_goTypes = []interface{}{
	(GenerateNewsfeedResponse_GenerateNewsfeedStatus)(0), // 0: newsfeed.GenerateNewsfeedResponse.GenerateNewsfeedStatus
	(*GenerateNewsfeedRequest)(nil),                      // 1: newsfeed.GenerateNewsfeedRequest
	(*GenerateNewsfeedResponse)(nil),                     // 2: newsfeed.GenerateNewsfeedResponse
}
var file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_depIdxs = []int32{
	0, // 0: newsfeed.GenerateNewsfeedResponse.status:type_name -> newsfeed.GenerateNewsfeedResponse.GenerateNewsfeedStatus
	1, // 1: newsfeed.Newsfeed.GenerateNewsfeed:input_type -> newsfeed.GenerateNewsfeedRequest
	2, // 2: newsfeed.Newsfeed.GenerateNewsfeed:output_type -> newsfeed.GenerateNewsfeedResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_init() }
func file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_init() {
	if File_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateNewsfeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateNewsfeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_goTypes,
		DependencyIndexes: file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_depIdxs,
		EnumInfos:         file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_enumTypes,
		MessageInfos:      file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_msgTypes,
	}.Build()
	File_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto = out.File
	file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_rawDesc = nil
	file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_goTypes = nil
	file_internal_interfaces_proto_protobuf_newsfeed_newsfeed_proto_depIdxs = nil
}
