my_sql: &MYSQL
  dsn: "root:123456@tcp(localhost:3306)/socialnetwork?charset=utf8mb4&parseTime=True&loc=Local"
  defaultstringsize: 256
  disabledatetimeprecision: true
  dontsupportrenameindex: true
  skipinitializewithversion: false
redis: &REDIS
  addr: locallhost:6379
user_and_post_config:
  port: 8090
  my_sql: *MYSQL
  redis: *REDIS
newsfeed_config:
  port: 8091
  my_sql: *MYSQL
  redis: *REDIS
web_config:
  port: 8092
  user_and_post:
    hosts: ["locallhost:8090"]
  newsfeed:
    hosts: ["locallhost:8091"]